name: windows

on:
  push:
    branches: [ master ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up build variables
        run: bash ./.github/scripts/setup_build_variables.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          install-deps: 'true'
          arch: 'win64_msvc2019_64'

      - name: Set up nmake
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up SW
        run: |
          curl -L "https://software-network.org/client/sw-master-windows-client.zip" --output sw.zip
          7z x sw.zip -o"sw"
          cd sw
          ./sw.exe setup

      - name: Set up SW path
        run: echo "D:\a\ksnip-plugin-ocr\ksnip-plugin-ocr\sw" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build and install leptonica
        run: |
          git clone --depth 1 https://github.com/DanBloomberg/leptonica.git
          cd leptonica
          mkdir build
          cd build && cmake .. -G"NMake Makefiles" -DCMAKE_INSTALL_PREFIX="$env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_PROG=OFF
          nmake
          nmake install

      - name: Build and install tessarect
        run: |
          git clone --depth 1 https://github.com/tesseract-ocr/tesseract.git
          cd tesseract
          mkdir build
          cd build && cmake .. -G"NMake Makefiles" -DCMAKE_INSTALL_PREFIX="$env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_TRAINING_TOOLS=OFF -DOPENMP_BUILD=OFF
          nmake
          nmake install
          ln -s $env:INSTALL_PREFIX/lib/tesseract50.lib $env:INSTALL_PREFIX/lib/tesseract.lib

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G"NMake Makefiles" -DCMAKE_PREFIX_PATH="$env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=Release
          nmake